global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'dogechain'
    scrape_interval: 5s
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets:
        - '10.5.0.11:9090'
        - '10.5.0.12:9090'
        - '10.5.0.13:9090'
        - '10.5.0.14:9090'
        - '10.5.0.15:9090'
